[package]
name = "http_api"
version = "0.1.0"

[application]
mod = "http_api::app"

[dependencies]
cowboy = "2.12.0"
cowlib = "2.13.0"
ranch = "2.1.0"
serde = { path = "../serde" }
serde_json = { path = "../serde_json" }
